name: Fetch Fyers Live Data

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas fyers-apiv3 pyotp requests

            - name: Run Script
        env:
          # डावीकडील नावे पायथन कोड वाचेल आणि उजवीकडील नावे तुमच्या गिटहब सेटिंग्जमधील आहेत
          FY_APP_ID: ${{ secrets.FY_ACCESS_TOKEN }}   # 👈 हे सुधारले आहे (तुमचा Client ID यात आहे)
          FY_SECRET_KEY: ${{ secrets.FY_SECRET_KEY }}
          FY_TOTP_KEY: ${{ secrets.FY_TOTP_KEY }}
          FY_PIN: ${{ secrets.FY_PIN }}
          FYERS_ID: ${{ secrets.FY_USER_ID }}         # 👈 हे सुधारले आहे (तुमचा User ID यात आहे)
        run: python cloud_expiry.py

